# Generated by Django 4.1.13 on 2025-03-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_news_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views_count',
        ),
    ]
